# Generated by Django 5.0.1 on 2025-04-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_user_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditTrail',
        ),
    ]
